version: "3.7"
services:
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=example
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      #- ./mysql_data/:/var/lib/mysql/
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysql_log:/var/log/mysql
    networks:
      - elastic
  elasticsearch:
    image: elasticsearch:7.7.0
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - discovery.seed_hosts=elasticsearch
      - cluster.name=bylee
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      - network.host=0.0.0.0
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    image: kibana:7.7.0
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - elasticsearch
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.7.0
    user: root
    networks:
      - elastic
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - ./metricbeat_system.yml:/usr/share/metricbeat/modules.d/system.yml
      - ./metricbeat_mysql.yml:/usr/share/metricbeat/modules.d/mysql.yml
    # disable strict permission checks
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    depends_on:
      - elasticsearch
      - kibana
      - mysql
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    user: root
    networks:
      - elastic
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./mysql_log/error.log:/usr/share/filebeat/error.log
      - ./mysql_log/slow.log:/usr/share/filebeat/slow.log
      - ./filebeat_system.yml:/usr/share/filebeat/modules.d/system.yml
      - ./filebeat_mysql.yml:/usr/share/filebeat/modules.d/mysql.yml
      - /private/var/log/system.log:/usr/share/filebeat/system.log
    # disable strict permission checks
    command: ["--strict.perms=false"]
    depends_on:
      - elasticsearch
      - kibana
      - mysql
volumes:
  elasticsearch_data:
  #mysql_data:

networks:
  elastic:
